apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  containers:
  - name: kafka-producer
    image: quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
    command:
    - sh
    - -c
    args:
    - |
      bin/kafka-console-producer.sh --broker-list my-kafka-cluster-kafka-bootstrap:9092 --topic my-topic
    tty: true
    stdin: true
  restartPolicy: Never
